export const UI_REVIEW_SCENARIOS = [
  "workspace-briefing",
  "workspace-monitor",
  "workspace-broadcast",
  "broadcast-indexing",
  "broadcast-current",
  "broadcast-paused",
  "broadcast-partial",
  "broadcast-empty",
  "broadcast-lagging",
  "broadcast-failed",
  "workspace-extensions",
  "workspace-plan",
  "workspace-materials",
  "materials-warehouse-attention",
  "production-pathway",
  "workspace-population",
  "workspace-markets",
  "markets-indexing",
  "markets-paused",
  "markets-partial",
  "markets-empty",
  "markets-lagging",
  "markets-failed",
  "population-probe-missing",
  "archive-latest",
  "archive-historical",
  "critical-task-loading",
  "critical-task-failed",
  "dialog-language",
  "dialog-theme",
  "dialog-settings",
  "dialog-observation",
  "dialog-diagnostics",
  "dialog-legal",
  "dialog-research",
  "dialog-recovery",
  "notification-error",
  "tooltip-contextual",
  "attention-cue",
  "keyboard-focus",
  "native-dropdown",
] as const;

export type UiReviewScenarioId = (typeof UI_REVIEW_SCENARIOS)[number];
export type UiReviewThemeId = "classic" | "high-contrast" | "boundary";
